### ISSUE TITLE
Issue on grab URL after all credential insert

### ISSUE THREAD

**Issue by devilLof** [fernandostc/DS-Block-by-Hash-File-Automation#1]
Hi fernandostc, when I try to use the code I got problem on the connection of URL.
It show me DSP virtual environment python script error. As the new python environment no longer use old version of python2, could it be problem on this? And the virtual environment also a new version. Could you advice me on this?

**Comment by fernandostc** [comment]
- In the repo you have the requirements versioning for it. I'm using Python 3 for this project

**Comment by devilLof** [comment]
Yup I'm using python 3. But I find out some error code as below.

![16334500703581117683828175286574](https://user-images.githubusercontent.com/87362404/136060993-e9450d21-87d4-42a6-82b7-34cfb35a9b2e.jpg)
![16334500982308227400036688601353](https://user-images.githubusercontent.com/87362404/136061103-1010853c-ec42-48b6-bee5-f4a1a6271f08.jpg)

**Comment by fernandostc** [comment]
Does your API communication is enabled on Deep Security Manager?
Which DSM version are you using?

**Comment by devilLof** [comment]
Hi sir, I had enabled it. I'm using ver 20

**Comment by fernandostc** [comment]
Ok. To help you in a better way could we schedule a remote session and I can help you with it?
Here is my email fernando_cardoso@trendmicro.com

**Comment by devilLof** [comment]
Sure. May I know your GMT hour? So I can adjust a best time.

**Comment by devilLof** [comment]
Hi Fernando,

I sent you an email. 

Thanks.

**Comment by fernandostc** [comment]
Closed
